### ISSUE TITLE
filtering / sorting

### ISSUE THREAD

**Issue by dam13n** [shaun965/vote#4]
Are these questions just ordered willy nilly!? Let me get some sort by date (most recent and oldest) and total vote count.

**Comment by shaun965** [comment]
Included a simple sort by vote count

**Comment by dam13n** [comment]
Just fyi, this type of sorting (by vote count), while do-able using mongo, is something that sql dbs excel at (using joins).

You wouldn't notice the issues until you have a lot more data. You could "embed" vote details in questions though, which would largely help mitigate the issue. Indexing probably makes a big difference too. I wish I had some actual figures to present on this...

In the future when you make your own projects, think critically about your data structure before choosing a db type. I know I said mongo is fine for prototyping EVEN IF you plan to switch to a sql db (like Postgres), and it is, but just be aware. : )

Well done on everything so far.
